// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6bOdb7iDYlntteMN58oLR49WMbMWTreI',
    appId: '1:294815270505:web:d972a22c8076991a4284f8',
    messagingSenderId: '294815270505',
    projectId: 'final-year-project-59613',
    authDomain: 'final-year-project-59613.firebaseapp.com',
    storageBucket: 'final-year-project-59613.appspot.com',
    measurementId: 'G-FQLX6ZZ1HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL74LDTkdfkTHcUYtVNn-_G1-cUzZrNlg',
    appId: '1:294815270505:android:edf449116605a77f4284f8',
    messagingSenderId: '294815270505',
    projectId: 'final-year-project-59613',
    storageBucket: 'final-year-project-59613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDULqi1DsJerslicFBqVkhFhqBr4mcGYYY',
    appId: '1:294815270505:ios:86b7d17ffd7fe2cc4284f8',
    messagingSenderId: '294815270505',
    projectId: 'final-year-project-59613',
    storageBucket: 'final-year-project-59613.appspot.com',
    iosClientId: '294815270505-f6bv49saq109gjhp7rm5iiq181ephuun.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDULqi1DsJerslicFBqVkhFhqBr4mcGYYY',
    appId: '1:294815270505:ios:86b7d17ffd7fe2cc4284f8',
    messagingSenderId: '294815270505',
    projectId: 'final-year-project-59613',
    storageBucket: 'final-year-project-59613.appspot.com',
    iosClientId: '294815270505-f6bv49saq109gjhp7rm5iiq181ephuun.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
