// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
 //import 'firebase_options.dart';

// await Firebase.initializeApp(
//  options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-IMoK2rhcT_qHQODzOWXx6KPgH27m2Yg',
    appId: '1:623262723962:web:68aaddc6a3fbb9efbdb0c3',
    messagingSenderId: '623262723962',
    projectId: 'ehrproj-406af',
    authDomain: 'ehrproj-406af.firebaseapp.com',
    storageBucket: 'ehrproj-406af.appspot.com',
    measurementId: 'G-TFD56J708D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTyE_0KsqILCpVKcBd4opxL0w76lYZElc',
    appId: '1:623262723962:android:b4fe5b8dfb5bb7fdbdb0c3',
    messagingSenderId: '623262723962',
    projectId: 'ehrproj-406af',
    storageBucket: 'ehrproj-406af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIatGQkhX7ol2gV0A7LDgXMwX36x_lMs4',
    appId: '1:623262723962:ios:46bfbc0b292d3bf1bdb0c3',
    messagingSenderId: '623262723962',
    projectId: 'ehrproj-406af',
    storageBucket: 'ehrproj-406af.appspot.com',
    iosClientId: '623262723962-ll6r75s63u7hn6e5rsl6bg4njk0mpbij.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIatGQkhX7ol2gV0A7LDgXMwX36x_lMs4',
    appId: '1:623262723962:ios:46bfbc0b292d3bf1bdb0c3',
    messagingSenderId: '623262723962',
    projectId: 'ehrproj-406af',
    storageBucket: 'ehrproj-406af.appspot.com',
    iosClientId: '623262723962-ll6r75s63u7hn6e5rsl6bg4njk0mpbij.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
